### PR TITLE
add -Wno-unused-but-set-variable

### PR DESCRIPTION
**Pull request by jtolio**
http://gcc.gnu.org/gcc-4.6/porting_to.html

### CODE REVIEW

**Comment by ccutrer** [comment]
Instead of blocking the warning completely, I fixed the one place that it was cropping up.

**Comment by jtolio** [comment]
it's cropping up in more than once place if you compile without debug mode

**Comment by ccutrer** [comment]
any others? I configured with ./configure --disable-assert --disable-shared, with both GCC and clang on precise, and this is the only one I found

**Comment by jtolio** [comment]
yep, that looks like that's it.

**Pull request closed without merging**
